#developement
# default: &default
#   adapter: postgresql
#   encoding: unicode

#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: task_management_backend_development

# test:
#   <<: *default
#   database: task_management_backend_test


# production:
#   <<: *default
#   database: task_management_backend_production
#   username: task_management_backend
#   password: <%= ENV["TASK_MANAGEMENT_BACKEND_DATABASE_PASSWORD"] %>



#production 
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_management_backend_development

test:
  <<: *default
  database: task_management_backend_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
